export enum Events {
  REQUEST_FRIENDSHIP = 'REQUEST_FRIENDSHIP',
  CANCEL_FRIENDSHIP_REQUEST = 'CANCEL_FRIENDSHIP_REQUEST',
  ACCEPT_FRIENDSHIP_REQUEST = 'ACCEPT_FRIENDSHIP_REQUEST',
  REJECT_FRIENDSHIP_REQUEST = 'REJECT_FRIENDSHIP_REQUEST'
}
